### PR TITLE
Fixed shorts in subscription feed hopefully

### PR DESCRIPTION
**Pull request by Ice-mourne**
The title says pretty much everything hopefully this works if there are problems let me know

### CODE REVIEW

**Comment by zevnda** [comment]
Thank you, I will review this PR when I have access to the new UI.

**Comment by Ice-mourne** [comment]
Found a new way of removing shorts using only CSS
```css
/* sub, home */
ytd-video-renderer:has([aria-label="Shorts"]),
/* trending */
ytd-rich-item-renderer:has([aria-label="Shorts"])  {
   display: none;
}
```
   CSS for removing the shorts button next to the home/sub
```css
#sections #items > ytd-guide-entry-renderer:has([title="Shorts"]) {
    display: none;
}
```

**Comment by sapondanaisriwan** [comment]
> Found a new way of removing shorts using only CSS
> ```css
> /* sub, home */
> ytd-video-renderer:has([aria-label="Shorts"]),
> /* trending */
> ytd-rich-item-renderer:has([aria-label="Shorts"])  {
>    display: none;
> }
> ```
>    CSS for removing the shorts button next to the home/sub
> ```css
> #sections #items > ytd-guide-entry-renderer:has([title="Shorts"]) {
>     display: none;
> }
> ```

The old browser does not support :has

**Comment by Ice-mourne** [comment]
> ... 
> The old browser does not support :has

First of all, it's not a new feature and people should update browsers more often than once a year (personally don't care about people who refuse to update I prefer giving a good experience to 99.9% instead of a mediocre 100%)
Second, because of how simple it is to implement this, there is no reason not to do it

Also testing out some improvements because just hiding it is not a great solution

**Comment by zevnda** [comment]
Fixed in 1.6.1 with [d8eda0e](https://github.com/ProbablyRaging/hide-youtube-shorts/commit/d8eda0e0b488fd0d5d2f3ba65244bc0e6df7acd6)

You can download the .zip from this repo and load the unpacked version or give it a couple of days to go live on CWS. 

Feel free to open a new issue if you have any more problems with the new UI

**Comment by Ice-mourne** [comment]
Actually I was testing some ideas but YouTube decided to change sub feed
again (it was broken) and had to keep it on hold
It's fixed since few days ago

I will take a look and implement that new idea if it's still needed

**Comment by zevnda** [comment]
Yeah it would seem that a lot of the people who had the changes early on have been rolled out and a new treatment group rolled in.

For sure, feel free to open a new PR with those changes or reopen/update this one. Happy to take a look!

**Pull request closed without merging**
